remote_theme: pages-themes/midnight@v0.2.0

# Disable default GitHub project buttons
show_downloads: false
is_project_page: false
github:
  is_project_page: false

# Custom Contribute link (used manually in index.md)
contribute_url: https://github.com/AaronAbraham420/Audio-Engineering-Wiki
contribute_text: Contribute

plugins:
  - jekyll-remote-theme